name: subscribed_stream
description: A utiliy class for easy stream subscription handling.
version: 0.0.1
homepage: https://github.com/HeroPhil/subscribed_stream

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:


dev_dependencies:
  flutter_lints: ^1.0.0